name: Bug Report
description: Use this template to report bugs.
labels: bug

body:
  - type: textarea
    attributes:
      label: 'Describe the bug'
      description: A clear and concise description of what the bug is.
        
  - type: textarea
    attributes:
      label: 'To Reproduce'
      description: 'Steps to reproduce the behavior.'
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
        
  - type: textarea
    attributes:
      label: 'Expected behavior'
      description: 'A clear and concise description of what you expected to happen.'
      placeholder: 'Describe what you expected to happen.'

  - type: input
    attributes:
      label: 'Mod Version'
      description: 'The version of the mod you are using.'
      placeholder: 'e.g., 1.2.3'
      
  - type: input
    attributes:
      label: 'Minecraft Version'
      description: 'The Minecraft version you are using.'
      placeholder: 'e.g., 1.20.1'
  
  - type: input
    attributes:
      label: 'Modloader'
      description: 'The modloader you are using.'
      placeholder: 'e.g., Forge/Fabric/NeoForge'

  - type: input
    attributes:
      label: 'Crash Log (if applicable)'
      description: 'If the game crashed, please provide the crash report. Please upload the log to [mclo.gs](https://mclo.gs/) or [Gist](https://gist.github.com/) and provide the link here'
      
  - type: textarea
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
      placeholder: 'Provide any additional details or observations that might help.'
